PUT http://localhost:8080/api/mangas/secure/return?mangaId=1
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJpSGFnZVUxLUxDQWZMVlVnck5SaHItZzBUQjVZZW4xcEwyaTc4YkRUUTZ3IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULk9WcS1WQnUybDVqNDVya0lRSlVzcnVxcDdSMDlGRkxrVkJhb3JxdE5seVUiLCJpc3MiOiJodHRwczovL2Rldi0yNzk4Mjk2NC5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NzQzMzIyNDEsImV4cCI6MTY3NDMzNTg0MSwiY2lkIjoiMG9hN3lwZmN2cmRreGJzd041ZDciLCJ1aWQiOiIwMHU3eXBkcjQxSGxoV2VlSjVkNyIsInNjcCI6WyJwcm9maWxlIiwib3BlbmlkIiwiZW1haWwiXSwiYXV0aF90aW1lIjoxNjc0MzMyMjM5LCJzdWIiOiJ0ZXN0dXNlckBlbWFpbC5jb20ifQ.TNmTdkdP8vDejY7x2ICKBp4k0n07VwYl4xWFqwOTW5pXHQhY1LPWBAVtRd3NyW9TvbP-AP6ThBnPiuZKkvIn9PqSN959MtDRebJ_QLiE5sYqW0DKnISvzef1bccRqpXj4stFDtKIkWzrqWB4Bd6zvAooq_4FxKVeMXPQA9Ruz7ug2x75QLjY_nAIlD2AHPHw1LdLGB9bRXUTsRdoPTx-jHG00rHjWJIoxPWi2izSLy0V3kplVPv9EGiqeLxszaaEhgrmAst8LegCrg2NyEoE8ViLvyGKFdkYWm7dddrqaP5ykddXjOFJlgcvZLdceQ96GLTHbsH3JKXczVvsWWeIow
